version: 2.1
executors:
  fedora:
    docker:
      - image: registry.fedoraproject.org/fedora
    shell: /usr/bin/bash

jobs:
  build:
    executor: fedora
    steps:
      - run:
          name: Install compiler and tools
          command: >
            sudo dnf install --assumeyes --setopt=install_weak_deps=False
            cargo git make rust
      - checkout
      - run:
          name: Fetch dependencies via Cargo
          command: >
            cargo fetch
      - run:
          name: Build project
          command: >
            make -j all
 
workflows:
  build:
    jobs:
      - build
